### ISSUE TITLE
change default user and password

### ISSUE THREAD

**Issue by Tom-246** [obeone/winbox-docker#5]
Hi!

I found your docker container and using it at the moment with unraid. 

As I don't know kasmvnc I kindly ask for your help.

Is there a way to change the login credentials as I don't want to use the defaults... Adding a new kasmvnc-user I cannot access the app anymore. 

Thank you,

Tom

**Comment by obeone** [comment]
Hi, sadly it's not easy to change username..
But for password, you can set `VNC_PW` env variable with the password you want !

Sorry if I didn't answered before, I didn't saw the issue :(

**Comment by obeone** [comment]
Feel free to re-open issue if you think it's one
