### ISSUE TITLE
Docker Image download slow

### ISSUE THREAD

**Issue by NiceRath** [obeone/winbox-docker#6]
The image download from `ghcr.io/obeone/winbox:latest` is pretty slow.
We have 500MBit/s download and it takes ~10min for the ~1GB image to download (~2MB/s).
Might be faster if you would put it on [docker hub](https://www.docker.com/products/docker-hub/) or some other cloud provider(s) (should be usable for free)

**Comment by obeone** [comment]
Hi,

It's available on docker hub too 😄 

https://hub.docker.com/r/obeoneorg/winbox

**Comment by NiceRath** [comment]
Good to know 😅
It may be nice if the images shown in the Readme would be the ones with faster download speeds - as most people will just copy-paste it (:

Have a nice day
